Add authentication with Keycloak for scraping
meilisearch/docs-scraper pull request #73
Opened 2020-10-22 12:24 UTC by spahrson

This PR add the ability to authenticate by Keycloak.

2020-10-26 13:38 UTC, curquiza commented
Hello @spahrson!
Thanks for this PR, it seems to be a great addition! I don't know keycloak, can you tell me a little bit about it? What is your usage of keycloak for example?
I will discuss about it with the team and I will come back to you before the end of the week 🙂 But it should be ok!

2020-10-26 17:47 UTC, spahrson commented
Hi @curquiza.

Keycloak is a open source identity and access management solution. It can act as an OAuth 2.0 and OpenID connect compliant authorization server and there is a proxy called Gatekeeper to protect non-oauth compliant applications. We use Keycloak as Single-Sign-on solution. We use antora for documentation and meilisearch to search our documentation. Our antora instances are protected by Keycloak. So we need the ability to scrape antora for meilisearch using an OAuth 2.0 Bearer-Token. This PR fullfills this requirement for Keycloak.

2020-10-29 17:34 UTC, curquiza requested changes
Thanks again for your PR, I request some small changes but the general work is really good 🙂

---

I don't know if you already know this on GitHub but here is my tip: you can accept the change suggestions directly on the GitHub interface here (this is an example):
<img width="944" alt="Capture d’écran 2020-09-30 à 12 59 48" src="https://user-images.githubusercontent.com/20380692/97610156-cca58600-1a14-11eb-873a-0bee5c6c7011.png">

2020-10-29 17:34 UTC, curquiza commented on README.md
> +    - [Keycloak Access: Identity and Access Management](#keycloak-access-identity-and-access-management)
```suggestion
```

2020-10-29 17:34 UTC, curquiza commented on README.md
> +If you need to scrape site protected by Keycloak (Gatekeeper), you have to provide a valid Access Token.
```suggestion
If you need to scrape site protected by [Keycloak](https://github.com/keycloak/keycloak) (Gatekeeper), you have to provide a valid access token.
```

2020-10-29 17:34 UTC, curquiza commented on README.md
> +If you set the env variables `KC_URL`, `KC_REALM`, `KC_CLIENT_ID` and `KC_CLIENT_SECRET` the scraper authenticates himself against Keycloak using _Client Credentials Grant_ and adds the resulting Acc
```suggestion
If you set the environment variables `KC_URL`, `KC_REALM`, `KC_CLIENT_ID`, and `KC_CLIENT_SECRET` the scraper authenticates itself against Keycloak using _Client Credentials Grant_ and adds the resulting access token as `Authorization` HTTP header to each scraping request.
```

2020-10-29 17:34 UTC, curquiza commented on scraper/src/index.py
> +
Could you remove the empty space in this line?
Plus the file should end with a new line 🙂

2020-10-29 19:48 UTC, curquiza approved these changes
Awesome @spahrson! Thanks for your reactivity!!

2020-10-29 19:48 UTC, curquiza commented
bors merge

2020-10-29 19:51 UTC, merged